### ISSUE TITLE
README.md needs info for managed_content

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#149]
need to add info how to access it

**Comment by handrews** [comment]
Are you talking about how to set up the submodule or how to interact with it through the admin UI?  Or both?

**Comment by jochengcd** [comment]
The setup, because otherwise the site doesn't start.

**Comment by handrews** [comment]
As it turns out, there's a better solution.  I had made gcd-managed-content a submodule because I wanted to make it a bit easier to set up, as you could not (in 1.4, and maybe not 1.6) conditionally include a template.  Includes were processed before conditionals.  By 1.7, this was fixed and
conditionals are evaluated first.  So I will just add a USE_TEMPLATESADMIN setting that defaults to False.  For the front page and editing queue message, I'll make it show an explanation.  The ads will just disappear (they're nearly always already unincluded in dev setups anyway).

**Comment by handrews** [comment]
This is now documented by showing instructions for managed_content as the default text for the front page when managed_content is not deployed.  I'll cover it in the general docs update that I'm slowly working on as well, but this is no longer a blocking issue.
