### ISSUE TITLE
series edits with old format field

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#166]
When an indexer moves the old format to the new fields, he does not see them, even though the approver does.
But when approved, they re-appear.
See for example: http://www.comics.org/series/63682/

Something is odd there. Hitting reload a couple of times when editing a series with existing old format entries sometimes show the field it at the right place at the top with content, and sometimes does show it at the bottom with no content ?

**Comment by handrews** [comment]
@jochengcd I can get the field to bounce between the top and the bottom after removing the old format data and filling out the new fields, but the old format field is always empty after that point for me.

I'm not sure I'm interpreting this issue correctly.  The problem is that the indexer removes the old format text, fills out the new format fields, and submits, but the old format text is still in the old format field anyway?  I have not been able to reproduce this on the beta site so far.

**Comment by jochengcd** [comment]
Sometimes the indexer doesn't see the old format field at the beginning i.e. not at all. Then of course he won't change it. Not sure what happens after clearing it, but even that jumping is odd.

I think I played a bit around with compressing the CSS, i.e. the setting, but I think it should be active on beta right now ?

**Comment by jochengcd** [comment]
Thought I had a way (putting the modifying the form at a different place in the code and therefore processing workflow), but that was more due to a freshly started server. I.e. after a server restart the old format field shows and can be edited, but after a while it disappears from the usual place, and shows empty at the bottom.

**Comment by jochengcd** [comment]
since we migrated all the remaining format entries, we don't need to fix this bug.
