### ISSUE TITLE
Bug 801: enforce approved genres for offline indexing

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#234]
Originally Opened: 2013-04-14 09:35 PST

Now that we switch to the approved genre list while editing it should also be enforced/checked when importing story data.

**Comment by bookcats** [comment]
I've found some unapproved genres in the database recently, I think due to not enforcing the genre list on flat file/csv/text file indexing. One thought I had was that when you use the upload tool there could be an automatic comment added to the changeset to let the approver know that the tool had been used and the genres should be checked more carefully. It would be better, of course, to check them and not allow the file to be uploaded if it contains non-standard genres.
