### ISSUE TITLE
changeset editing access

### ISSUE THREAD

**Issue by ddmilne** [GrandComicsDatabase/gcd-django#500]
Dave Porta has informed me of the following problem that he sees when editors return a changeset to him for editing.  He is working on an Android Moto E4 and suspects that it does not display as intended.  I have verified that I do not see the problem on my Windows PC running Firefox.

    From his "Records You Are Editing" screen, when he clicks on the issue name it correctly opens his regular editing screen for that issue.  But, once at the editing screen, when he scrolls to the bottom he does NOT see the choices of submit, discard, or add a comment, or have the ability to directly make any edits.  He describes the screen as only showing him "...the list of sequences, the old stuff in black that I've edited, and what my new archiving looks like, in yellow. There's no "retract and edit further" option. It offers no access."

    I was not able to figure out how he has previously, successfully, made changes requested by editors and he could not describe how.

- Don Milne

**Comment by J-Garcke-SCAI** [comment]
He describes the compare page, from there are edit options for the sequences, if it is sent back to him or if it is in editing.

The compare page will be appear from the list of changes if the change is under review by an editor, then one cannot do changes. And there is no retract and edit, since it is under review.

If he wants to edit in such a case, the editor needs to send it back.

What he describes cannot happen when the editor returned the changeset.

**Comment by jochengcd** [comment]
He describes the compare page, from there are edit options for the sequences, if it is sent back to him or if it is in editing.

The compare page will be appear from the list of changes if the change is under review by an editor, then one cannot do changes. And there is no retract and edit, since it is under review.

If he wants to edit in such a case, the editor needs to send it back.

What he describes cannot happen when the editor returned the changeset.

**Comment by ddmilne** [comment]
Thanks.  I thought something similar when there was no explanation of how he had been able to edit previously.  But I told him I would send it in.
- Don
