### ISSUE TITLE
Linked issue list for feature is empty while linked sequence list is non-empty

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#598]
My expectation from the text in the link is that I would see the issues for whom a sequence exists with the tagged feature, but the issue lists are empty.

The linked creator list is also empty.

See https://www.comics.org/feature/29121/

**Comment by jochengcd** [comment]
added the disclaimer on that kind of lists are generated

**Comment by LegalizeAdulthood** [comment]
Why restrict the list to only comic stories?

If we are going to have features on text articles and stories, it only makes sense that we would treat them on equal footing.

**Comment by jochengcd** [comment]
Because we are comic database ?

The overview is meant to give the overview of comic stories. I don't think that users expect to see non-comic stories for comic features ?

Same as the issue list, we are restricting to the core sequences to not have other sequences cluttering the lists.

One always gets all sequences with the sequence list.

To have usable overviews for all sequence types would need further filtering possibilities to be able to focus on the relevant ones for the specific task.

**Comment by LegalizeAdulthood** [comment]
That makes sense.
