### ISSUE TITLE
tequan

### ISSUE THREAD

**Issue by tequan394** [GrandComicsDatabase/gcd-django#642]
Occurred at https://www.comics.org/accounts/confirm/f48ff299eaf5862c7150b6d140bc86b5e64a5055/%3Cbr

**Comment by adia** [comment]
You tried to confirm your account and got an error? It seems there were some extra characters at the end of the link above, the "%3Cbr" at the end shouldn't be there.

I accidentally clicked the link and confirmed your account - sorry about that. Please tell us if there's any other problem, otherwise I'll close this report. Thanks!
